# Generated by Django 4.2.5 on 2023-10-04 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='item',
        ),
        migrations.DeleteModel(
            name='todo',
        ),
    ]
