# Generated by Django 5.0.2 on 2024-10-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main1', '0002_delete_item_delete_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='artist_images/')),
                ('biography', models.TextField()),
                ('stock_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
